-- supabase/migrations/0004_add_weekend_to_attendance_status.sql
-- Modify check constraint on attendance table to allow 'weekend' status

-- Drop the autogenerated check constraint if it exists
alter table public.attendance drop constraint if exists attendance_status_check;

-- Re-add check constraint with 'weekend' as a valid state
alter table public.attendance add constraint attendance_status_check check (
  status in ('present', 'absent', 'half_day', 'leave', 'weekend')
);
